### ISSUE TITLE
NPE on instantiation when GroupID missing

### ISSUE THREAD

**Issue by kartius** [confluentinc/parallel-consumer#101]
Exception appeared in io.confluent.parallelconsumer.ParallelEoSStreamProcessor.checkAutoCommitIsDisabled.
Looks like `(ConsumerCoordinator)coordinatorField.get(consumer)` returns a null;

The code of a creation of ParallelStreamProcessor:

```
@Slf4j
@Component
public class ParallelConsumer {
    String inputTopic = "test-topic";

    public ParallelConsumer() {
        consume();
    }

    public ParallelStreamProcessor getParallelConsumer(){
        org.apache.kafka.clients.consumer.Consumer<String, String> kafkaConsumer = getKafkaConsumer(); // (1)

        ParallelConsumerOptions<String, String> options = ParallelConsumerOptions.<String, String>builder()
                .ordering(KEY) // (2)
                .maxConcurrency(1000) // (3)
                .consumer(kafkaConsumer)
                .build();

        ParallelStreamProcessor<String, String> eosStreamProcessor =
                ParallelStreamProcessor.createEosStreamProcessor(options);

        eosStreamProcessor.subscribe(of(inputTopic)); // (4)

        return eosStreamProcessor;
    }

    org.apache.kafka.clients.consumer.Consumer<String, String> getKafkaConsumer() {
        Properties properties = new Properties();
        properties.setProperty(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
        properties.setProperty(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
        properties.setProperty(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
        properties.setProperty(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "false");
        return new KafkaConsumer<>(properties);
    }

    public void consume () {
        getParallelConsumer().poll(record ->
                log.info("Concurrently processing a record: {}", record));
    }

}
```

**Comment by astubbs** [comment]
Thanks for the submission! Can you please return the entire stack trace? And ideally a unit test that reproduces it.

**Comment by astubbs** [comment]
Also, what version of Kafka client libraries are you pulling in?

**Comment by kartius** [comment]
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'parallelConsumer' defined in file [.../ParallelConsumer.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.amway.magic.bonus.kafka.ParallelConsumer]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1318) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1216) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923) ~[spring-context-5.3.3.jar:5.3.3]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588) ~[spring-context-5.3.3.jar:5.3.3]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) [spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) [spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) [spring-boot-2.4.2.jar:2.4.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [spring-boot-2.4.2.jar:2.4.2]
	at com.amway.magic.bonus.KafkaPocApplication.main(KafkaPocApplication.java:10) [classes/:na]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [ParallelConsumer]: Constructor threw exception; nested exception is java.lang.NullPointerException
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:225) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1310) ~[spring-beans-5.3.3.jar:5.3.3]
	... 18 common frames omitted
Caused by: java.lang.NullPointerException: null
	at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.checkAutoCommitIsDisabled(ParallelEoSStreamProcessor.java:323) ~[parallel-consumer-core-0.3.0.1.jar:na]
	at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.<init>(ParallelEoSStreamProcessor.java:204) ~[parallel-consumer-core-0.3.0.1.jar:na]
	at io.confluent.parallelconsumer.ParallelStreamProcessor.createEosStreamProcessor(ParallelStreamProcessor.java:27) ~[parallel-consumer-core-0.3.0.1.jar:na]
	at com.amway.magic.bonus.kafka.ParallelConsumer.getParallelConsumer(ParallelConsumer.java:35) ~[classes/:na]
	at com.amway.magic.bonus.kafka.ParallelConsumer.consume(ParallelConsumer.java:52) ~[classes/:na]
	at com.amway.magic.bonus.kafka.ParallelConsumer.<init>(ParallelConsumer.java:22) ~[classes/:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_281]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_281]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_281]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_281]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:212) ~[spring-beans-5.3.3.jar:5.3.3]
	... 20 common frames omitted
```
I downloaded apache kafka from https://kafka.apache.org/downloads the current version is 2.13-2.7.0

**Comment by astubbs** [comment]
Is it possible for you to upload a complete working example of the error?

**Comment by astubbs** [comment]
I ask because it seems you're running on 2.7, so I made a PR to test 2.7, and it seems to work fine. So I'd like to see more exactly what you're running

2.7: https://github.com/confluentinc/parallel-consumer/pull/104

**Comment by astubbs** [comment]
Ah, ok I think it's because you're not setting a group id. If there's no group, there's no coordinator. Was that intentional?

I'm working on an api option that doesn't need to do reflection, and so is safer. I'll post a link here when it's ready.

In the mean time, set a group id and the error should go away.

The issue is that Kafka doesn't check for group id presence, until we use `#subcribe`. But unfortunately, we need to check auto commit is disabled before that stage - so we trigger the NPE due to missing coordinator due to missing group id, before Kafka checks itself for a group id. It seems we can access transitively a check for group id presence, so the new patch will also leverage that.

**Comment by astubbs** [comment]
For a preview, see PR's #105 and #106 , NB they both have a non-master base branch currently.

**Comment by astubbs** [comment]
Btw where did you copy the example from? I'll make sure to add setting a group id to it.

**Comment by kartius** [comment]
@astubbs  - https://github.com/confluentinc/parallel-consumer getting from README example

**Comment by kartius** [comment]
@astubbs Thanks for you advice it's working for me. But also I have a question is it workable for jdk 8 ?

**Comment by astubbs** [comment]
Yes, the test suite runs on 8 to ensure this. Why do you ask? Any issues?

**Comment by kartius** [comment]
@astubbs Yes, I got an exception after running my spring boot container 
```
Caused by: java.lang.UnsupportedClassVersionError: pl/tlinkowski/unij/service/collect/jdk8/Jdk8UnmodifiableListFactory has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_281]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[na:1.8.0_281]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_281]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[na:1.8.0_281]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[na:1.8.0_281]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[na:1.8.0_281]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[na:1.8.0_281]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_281]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[na:1.8.0_281]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_281]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[na:1.8.0_281]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_281]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_281]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_281]
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370) ~[na:1.8.0_281]
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404) ~[na:1.8.0_281]
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480) ~[na:1.8.0_281]
	at java.lang.Iterable.forEach(Iterable.java:74) ~[na:1.8.0_281]
	at pl.tlinkowski.unij.api.UniJLoader.load(UniJLoader.java:42) ~[pl.tlinkowski.unij.api-0.1.1.jar:na]
	at pl.tlinkowski.unij.api.UniJ.listFactory(UniJ.java:32) ~[pl.tlinkowski.unij.api-0.1.1.jar:na]
	at pl.tlinkowski.unij.api.UniLists.of(UniLists.java:60) ~[pl.tlinkowski.unij.api-0.1.1.jar:na]
	at ...ParallelConsumer.getParallelConsumer(ParallelConsumer.java:37) ~[classes/:na]
	at ..ParallelConsumer.consume(ParallelConsumer.java:53) ~[classes/:na]
	at ..ParallelConsumer.<init>(ParallelConsumer.java:22) ~[classes/:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_281]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_281]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_281]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_281]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:212) ~[spring-beans-5.3.3.jar:5.3.3]
	... 20 common frames omitted
```

**Comment by astubbs** [comment]
@kartius sorry for the delay. Yes, that's due to https://github.com/confluentinc/parallel-consumer/issues/87 which is fixed, but unreleased. Am releasing the next fix version this week which will include both these fixes and others.

**Comment by kartius** [comment]
Thanks for your reply! @astubbs Could you also provide please proper release version?

**Comment by kartius** [comment]
I see that 0.3.0.1 version is current one which was containing this bug?

**Comment by astubbs** [comment]
Hi @kartius , this is fixed in 302. https://github.com/confluentinc/parallel-consumer/releases/tag/0.3.0.2
