### ISSUE TITLE
Appears to consume again from the start of the topic when it reaches at the end

### ISSUE THREAD

**Issue by mostafa-asg** [confluentinc/parallel-consumer#117]
Hi,
I just wanted to run a sample application and get a taste of `parallel-consumer`. My Kafka topic has only 2 messages: `hello` and `world`. I ran the `vertx` sample and wanted to create a HTTP request for each message. Unfortunately, it didn't work as expected and didn't fire any HTTP requests. What stranger behavior is that it starts reading from the start of the topic when it reaches the end.   
Here is the output:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
Concurrently constructing and returning RequestInfo from record world
Concurrently constructing and returning RequestInfo from record hello
Concurrently constructing and returning RequestInfo from record world
Concurrently constructing and returning RequestInfo from record hello
Concurrently constructing and returning RequestInfo from record world
Concurrently constructing and returning RequestInfo from record hello
Concurrently constructing and returning RequestInfo from record world
Concurrently constructing and returning RequestInfo from record hello
```
The main code `Driver.java`:
```Java
package com.github;

import io.confluent.parallelconsumer.ParallelConsumerOptions;
import io.confluent.parallelconsumer.vertx.JStreamVertxParallelStreamProcessor;
import io.confluent.parallelconsumer.vertx.VertxParallelEoSStreamProcessor.RequestInfo;
import io.vertx.core.buffer.Buffer;
import io.vertx.ext.web.client.HttpResponse;
import org.apache.kafka.clients.consumer.Consumer;
import org.apache.kafka.clients.consumer.KafkaConsumer;

import java.time.Duration;
import java.util.Collections;
import java.util.HashMap;
import java.util.Properties;

public class Driver {

    static String inputTopic = "test";

    Consumer<String, String> getKafkaConsumer() {
        Properties props = new Properties();
        props.put("key.deserializer", "org.apache.kafka.common.serialization.StringDeserializer");
        props.put("value.deserializer", "org.apache.kafka.common.serialization.StringDeserializer");
        props.put("bootstrap.servers", "localhost:9092");
        props.put("auto.offset.reset", "earliest");
        props.put("group.id","test");
        props.put("enable.auto.commit", false);
        return new KafkaConsumer<>(props);
    }

    JStreamVertxParallelStreamProcessor<String, String> parallelConsumer;

    void run() {
        Consumer<String, String> kafkaConsumer = getKafkaConsumer();
        var options = ParallelConsumerOptions.<String, String>builder()
                .ordering(ParallelConsumerOptions.ProcessingOrder.UNORDERED)
                .consumer(kafkaConsumer)
                .build();

        this.parallelConsumer = JStreamVertxParallelStreamProcessor.createEosStreamProcessor(options);
        parallelConsumer.subscribe(Collections.singleton(inputTopic));

        // tag::example[]
        var resultStream = parallelConsumer.vertxHttpReqInfoStream(record -> {
            System.out.println("Concurrently constructing and returning RequestInfo from record " + record.value());
            return new RequestInfo("https://httpbin.org", 80, "/get", new HashMap<>()); // <1>
        });
        // end::example[]


        resultStream.forEach(result -> {
            HttpResponse<Buffer> response = result.getAsr().result();
            System.out.println(response.bodyAsString());
        });

    }

    void close() {
        this.parallelConsumer.closeDrainFirst(Duration.ofSeconds(2));
    }

    public static void main(String[] args) {
        Driver driver = new Driver();
        Runtime.getRuntime().addShutdownHook(new Thread(driver::close));

        driver.run();
    }
}
```
Maven file:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>pconsumer</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <pconsumer.version>0.3.0.2</pconsumer.version>
    </properties>

    <dependencies>
        <!-- https://mvnrepository.com/artifact/io.confluent.parallelconsumer/parallel-consumer-core -->
        <dependency>
            <groupId>io.confluent.parallelconsumer</groupId>
            <artifactId>parallel-consumer-core</artifactId>
            <version>${pconsumer.version}</version>
        </dependency>

        <!-- https://mvnrepository.com/artifact/io.confluent.parallelconsumer/parallel-consumer-vertx -->
        <dependency>
            <groupId>io.confluent.parallelconsumer</groupId>
            <artifactId>parallel-consumer-vertx</artifactId>
            <version>${pconsumer.version}</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>11</release>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```
Java version:
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```
Any idea? Have I missed something?

**Comment by astubbs** [comment]
So it continues reading the same two messages forever?

**Comment by mostafa-asg** [comment]
exactly.

**Comment by astubbs** [comment]
It's not restarting the topic, it's failing to process the message it downloads, and continually retrying forever. 
You need to include a slf4j implementation so you can see the logs:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

So you aren't seeing the error logs being produced:
```
C:\Users\anton\.jdks\adopt-openjdk-13.0.2\bin\java.exe -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:53713,suspend=y,server=n -javaagent:C:\Users\anton\AppData\Local\JetBrains\IdeaIC2021.1\captureAgent\debugger-agent.jar -Dfile.encoding=UTF-8 -classpath "C:\Users\anton\IdeaProjects\untitled\target\classes;C:\Users\anton\.m2\repository\io\confluent\parallelconsumer\parallel-consumer-core\0.3.0.2\parallel-consumer-core-0.3.0.2.jar;C:\Users\anton\.m2\repository\org\apache\kafka\kafka-clients\2.5.1\kafka-clients-2.5.1.jar;C:\Users\anton\.m2\repository\com\github\luben\zstd-jni\1.4.4-7\zstd-jni-1.4.4-7.jar;C:\Users\anton\.m2\repository\org\lz4\lz4-java\1.7.1\lz4-java-1.7.1.jar;C:\Users\anton\.m2\repository\org\xerial\snappy\snappy-java\1.1.7.3\snappy-java-1.1.7.3.jar;C:\Users\anton\.m2\repository\com\github\bsideup\jabel\jabel-javac-plugin\0.3.0\jabel-javac-plugin-0.3.0.jar;C:\Users\anton\.m2\repository\net\bytebuddy\byte-buddy\1.10.14\byte-buddy-1.10.14.jar;C:\Users\anton\.m2\repository\net\bytebuddy\byte-buddy-agent\1.10.14\byte-buddy-agent-1.10.14.jar;C:\Users\anton\.m2\repository\pl\tlinkowski\unij\pl.tlinkowski.unij.api\0.1.3\pl.tlinkowski.unij.api-0.1.3.jar;C:\Users\anton\.m2\repository\pl\tlinkowski\unij\pl.tlinkowski.unij.service.api\0.1.3\pl.tlinkowski.unij.service.api-0.1.3.jar;C:\Users\anton\.m2\repository\pl\tlinkowski\unij\pl.tlinkowski.unij.bundle.jdk8\0.1.3\pl.tlinkowski.unij.bundle.jdk8-0.1.3.jar;C:\Users\anton\.m2\repository\pl\tlinkowski\unij\pl.tlinkowski.unij.service.collect.jdk8\0.1.3\pl.tlinkowski.unij.service.collect.jdk8-0.1.3.jar;C:\Users\anton\.m2\repository\pl\tlinkowski\unij\pl.tlinkowski.unij.service.misc.jdk8\0.1.3\pl.tlinkowski.unij.service.misc.jdk8-0.1.3.jar;C:\Users\anton\.m2\repository\io\confluent\parallelconsumer\parallel-consumer-vertx\0.3.0.2\parallel-consumer-vertx-0.3.0.2.jar;C:\Users\anton\.m2\repository\io\vertx\vertx-web-client\4.0.0.CR1\vertx-web-client-4.0.0.CR1.jar;C:\Users\anton\.m2\repository\io\vertx\vertx-web-common\4.0.0.CR1\vertx-web-common-4.0.0.CR1.jar;C:\Users\anton\.m2\repository\io\vertx\vertx-auth-common\4.0.0.CR1\vertx-auth-common-4.0.0.CR1.jar;C:\Users\anton\.m2\repository\io\vertx\vertx-core\4.0.0.CR1\vertx-core-4.0.0.CR1.jar;C:\Users\anton\.m2\repository\io\netty\netty-common\4.1.49.Final\netty-common-4.1.49.Final.jar;C:\Users\anton\.m2\repository\io\netty\netty-buffer\4.1.49.Final\netty-buffer-4.1.49.Final.jar;C:\Users\anton\.m2\repository\io\netty\netty-transport\4.1.49.Final\netty-transport-4.1.49.Final.jar;C:\Users\anton\.m2\repository\io\netty\netty-handler\4.1.49.Final\netty-handler-4.1.49.Final.jar;C:\Users\anton\.m2\repository\io\netty\netty-codec\4.1.49.Final\netty-codec-4.1.49.Final.jar;C:\Users\anton\.m2\repository\io\netty\netty-handler-proxy\4.1.49.Final\netty-handler-proxy-4.1.49.Final.jar;C:\Users\anton\.m2\repository\io\netty\netty-codec-socks\4.1.49.Final\netty-codec-socks-4.1.49.Final.jar;C:\Users\anton\.m2\repository\io\netty\netty-codec-http\4.1.49.Final\netty-codec-http-4.1.49.Final.jar;C:\Users\anton\.m2\repository\io\netty\netty-codec-http2\4.1.49.Final\netty-codec-http2-4.1.49.Final.jar;C:\Users\anton\.m2\repository\io\netty\netty-resolver\4.1.49.Final\netty-resolver-4.1.49.Final.jar;C:\Users\anton\.m2\repository\io\netty\netty-resolver-dns\4.1.49.Final\netty-resolver-dns-4.1.49.Final.jar;C:\Users\anton\.m2\repository\io\netty\netty-codec-dns\4.1.49.Final\netty-codec-dns-4.1.49.Final.jar;C:\Users\anton\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.11.3\jackson-core-2.11.3.jar;C:\Users\anton\.m2\repository\ch\qos\logback\logback-classic\1.3.0-alpha5\logback-classic-1.3.0-alpha5.jar;C:\Users\anton\.m2\repository\ch\qos\logback\logback-core\1.3.0-alpha5\logback-core-1.3.0-alpha5.jar;C:\Users\anton\.m2\repository\com\sun\mail\javax.mail\1.6.2\javax.mail-1.6.2.jar;C:\Users\anton\.m2\repository\javax\activation\activation\1.1\activation-1.1.jar;C:\Users\anton\.m2\repository\edu\washington\cs\types\checker\checker-framework\1.7.0\checker-framework-1.7.0.jar;C:\Users\anton\.m2\repository\org\slf4j\slf4j-api\2.0.0-alpha1\slf4j-api-2.0.0-alpha1.jar;C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.2\lib\idea_rt.jar" com.github.Driver
Connected to the target VM, address: '127.0.0.1:53713', transport: 'socket'
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
39:01.954  INFO  [main]  (ParallelEoSStreamProcessor.java:202)#<init> Confluent Parallel Consumer initialise... Options: ParallelConsumerOptions(consumer=org.apache.kafka.clients.consumer.KafkaConsumer@3406472c, producer=null, ordering=UNORDERED, commitMode=PERIODIC_CONSUMER_ASYNCHRONOUS, maxConcurrency=16, defaultMessageRetryDelay=PT1S)
39:02.387  INFO  [main]  (ParallelEoSStreamProcessor.java:621)#supervisorLoop Control loop starting up...
39:02.562  INFO  [pc-broker-poll]  (ParallelEoSStreamProcessor.java:319)#onPartitionsAssigned Assigned 1 total (1 new) partition(s) [test-0]
Concurrently constructing and returning RequestInfo from record {"value0":"value","value1":[1,2,65765765765]}
39:07.736  ERROR [vert.x-eventloop-thread-1]  (VertxParallelEoSStreamProcessor.java:178)#lambda$vertxHttpWebClient$4 Vert.x Vertical fail: failed to resolve 'https://httpbin.org'. Exceeded max queries per resolve 4 
Concurrently constructing and returning RequestInfo from record {"value0":"value","value1":[1,2,65765765765]}
39:08.757  ERROR [vert.x-eventloop-thread-1]  (VertxParallelEoSStreamProcessor.java:178)#lambda$vertxHttpWebClient$4 Vert.x Vertical fail: failed to resolve 'https://httpbin.org'. Exceeded max queries per resolve 4 
Concurrently constructing and returning RequestInfo from record {"value0":"value","value1":[1,2,65765765765]}
39:09.782  ERROR [vert.x-eventloop-thread-1]  (VertxParallelEoSStreamProcessor.java:178)#lambda$vertxHttpWebClient$4 Vert.x Vertical fail: failed to resolve 'https://httpbin.org'. Exceeded max queries per resolve 4 
Concurrently constructing and returning RequestInfo from record {"value0":"value","value1":[1,2,65765765765]}
39:10.803  ERROR [vert.x-eventloop-thread-1]  (VertxParallelEoSStreamProcessor.java:178)#lambda$vertxHttpWebClient$4 Vert.x Vertical fail: failed to resolve 'https://httpbin.org'. Exceeded max queries per resolve 4 
Concurrently constructing and returning RequestInfo from record {"value0":"value","value1":[1,2,65765765765]}
39:11.824  ERROR [vert.x-eventloop-thread-1]  (VertxParallelEoSStreamProcessor.java:178)#lambda$vertxHttpWebClient$4 Vert.x Vertical fail: failed to resolve 'https://httpbin.org'. Exceeded max queries per resolve 4 
Concurrently constructing and returning RequestInfo from record {"value0":"value","value1":[1,2,65765765765]}
39:12.851  ERROR [vert.x-eventloop-thread-1]  (VertxParallelEoSStreamProcessor.java:178)#lambda$vertxHttpWebClient$4 Vert.x Vertical fail: failed to resolve 'https://httpbin.org'. Exceeded max queries per resolve 4 
Concurrently constructing and returning RequestInfo from record {"value0":"value","value1":[1,2,65765765765]}
39:13.874  ERROR [vert.x-eventloop-thread-1]  (VertxParallelEoSStreamProcessor.java:178)#lambda$vertxHttpWebClient$4 Vert.x Vertical fail: failed to resolve 'https://httpbin.org'. Exceeded max queries per resolve 4 
Concurrently constructing and returning RequestInfo from record {"value0":"value","value1":[1,2,65765765765]}
Disconnected from the target VM, address: '127.0.0.1:53713', transport: 'socket'
39:14.900  ERROR [vert.x-eventloop-thread-1]  (VertxParallelEoSStreamProcessor.java:178)#lambda$vertxHttpWebClient$4 Vert.x Vertical fail: failed to resolve 'https://httpbin.org'. Exceeded max queries per resolve 4 
39:14.901  INFO  [Thread-0]  (VertxParallelEoSStreamProcessor.java:269)#close Vert.x async consumer closing...
39:14.901  INFO  [Thread-0]  (ParallelEoSStreamProcessor.java:456)#close Signaling to close...
39:14.901  INFO  [Thread-0]  (ParallelEoSStreamProcessor.java:460)#close Will wait for all in flight to complete before
39:14.901  INFO  [Thread-0]  (ParallelEoSStreamProcessor.java:482)#waitForClose Waiting on closed state...
Concurrently constructing and returning RequestInfo from record {"value0":"value","value1":[1,2,65765765765]}
39:15.923  ERROR [vert.x-eventloop-thread-1]  (VertxParallelEoSStreamProcessor.java:178)#lambda$vertxHttpWebClient$4 Vert.x Vertical fail: failed to resolve 'https://httpbin.org'. Exceeded max queries per resolve 4 
39:16.912  ERROR [Thread-0]  (ParallelEoSStreamProcessor.java:494)#waitForClose Execution or timeout exception while waiting for the control thread to close cleanly (state was draining). Try increasing your time-out to allow the system to drain, or close withing draining.
java.util.concurrent.TimeoutException: null
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204) ~[na:na]
	at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.waitForClose(ParallelEoSStreamProcessor.java:487) ~[parallel-consumer-core-0.3.0.2.jar:na]
	at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.close(ParallelEoSStreamProcessor.java:469) ~[parallel-consumer-core-0.3.0.2.jar:na]
	at io.confluent.parallelconsumer.vertx.VertxParallelEoSStreamProcessor.close(VertxParallelEoSStreamProcessor.java:270) ~[parallel-consumer-vertx-0.3.0.2.jar:na]
	at io.confluent.parallelconsumer.DrainingCloseable.closeDrainFirst(DrainingCloseable.java:54) ~[parallel-consumer-core-0.3.0.2.jar:na]
	at com.github.Driver.close(Driver.java:60) ~[classes/:na]
	at java.base/java.lang.Thread.run(Thread.java:830) ~[na:na]
Exception in thread "Thread-0" java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.waitForClose(ParallelEoSStreamProcessor.java:487)
	at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.close(ParallelEoSStreamProcessor.java:469)
	at io.confluent.parallelconsumer.vertx.VertxParallelEoSStreamProcessor.close(VertxParallelEoSStreamProcessor.java:270)
	at io.confluent.parallelconsumer.DrainingCloseable.closeDrainFirst(DrainingCloseable.java:54)
	at com.github.Driver.close(Driver.java:60)
	at java.base/java.lang.Thread.run(Thread.java:830)

Process finished with exit code 130
```

The host in the req info should only be a host name, not a protocol. I.e. change
```
            return new RequestInfo("https://httpbin.org", 80, "/get", new HashMap<>()); // <1>

```
to
```
            return new RequestInfo("httpbin.org", 80, "/get", new HashMap<>()); // <1>
```

**Comment by astubbs** [comment]
@mostafa-asg would something like this be useful? It looks like this:

```
=========
   JUNIT started:    testLoggingCheck() (testLoggingCheck())
=========

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

---
Parallel Consumer: No SLF4J implementation detected - you will not get any log messages, including notification of issues 
processing messages. Please note the SLF4J errors printed above, and add a logging implementation.
---
```
