### ISSUE TITLE
NullPointerException in PartitionMonitor during Rebalancing

### ISSUE THREAD

**Issue by nioertel** [confluentinc/parallel-consumer#189]
Hi,

we're testing a pre-version of the Parallel Consumer from the [features/batching](/confluentinc/parallel-consumer/tree/features/batching) branch. I however suspect that the issue we see is not related to the changes on that branch.

**Setup:**
We have two topics with multiple partitions each and we have two consumer groups with multiple consumers in each group which are starting up pretty much in parallel.
**Problem:**
Sometimes during startup we see an exception like this, which seems to be related to a race condition when accessing the PartitionMonitor while a rebalancing is happening:
```
[INFO ] 2022-02-07 14:56:32.237 [pc-pool-2-thread-2]  o.a.k.c.u.AppInfoParser - Kafka version: 2.6.0
[INFO ] 2022-02-07 14:56:32.237 [pc-pool-2-thread-2]  o.a.k.c.u.AppInfoParser - Kafka commitId: 62abe01bee039651
[INFO ] 2022-02-07 14:56:32.238 [pc-pool-2-thread-2]  o.a.k.c.u.AppInfoParser - Kafka startTimeMs: 1644242192237
[INFO ] 2022-02-07 14:56:32.301 [kafka-producer-network-thread | producer-1]  o.a.k.c.Metadata - [Producer clientId=producer-1] Cluster ID: jfbZl7cxTwmF0aBasWKl1A
[INFO ] 2022-02-07 14:56:32.317 [pc-pool-2-thread-1]  p.t.u.a.UniJLoader - pl.tlinkowski.unij.service.api.collect.UnmodifiableListFactory service: selected pl.tlinkowski.unij.service.collect.jdk8.Jdk8UnmodifiableListFactory (priority=40)
[INFO ] 2022-02-07 14:56:33.117 [pc-broker-poll]  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=consumer-test-consumer-group-2, groupId=test-consumer-group] Attempt to heartbeat failed since group is rebalancing
[INFO ] 2022-02-07 14:56:33.119 [pc-broker-poll]  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=consumer-test-consumer-group-2, groupId=test-consumer-group] Revoke previously assigned partitions test-topic-14, test-topic-12, test-topic-13, test-topic-10, test-topic-11
[INFO ] 2022-02-07 14:56:33.120 [pc-broker-poll]  i.c.p.s.PartitionMonitor - Partitions revoked: [test-topic-14, test-topic-12, test-topic-13, test-topic-10, test-topic-11]
[INFO ] 2022-02-07 14:56:33.124 [pc-broker-poll]  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=consumer-test-consumer-group-2, groupId=test-consumer-group] (Re-)joining group
[INFO ] 2022-02-07 14:56:33.139 [pc-broker-poll]  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=consumer-test-consumer-group-1, groupId=test-consumer-group] Attempt to heartbeat failed since group is rebalancing
[INFO ] 2022-02-07 14:56:33.139 [pc-broker-poll]  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=consumer-test-consumer-group-1, groupId=test-consumer-group] Revoke previously assigned partitions other-test-topic-0, other-test-topic-2, other-test-topic-1, other-test-topic-4, other-test-topic-3, other-test-topic-5
[INFO ] 2022-02-07 14:56:33.175 [pc-broker-poll]  i.c.p.s.PartitionMonitor - Partitions revoked: [other-test-topic-0, other-test-topic-2, other-test-topic-1, other-test-topic-4, other-test-topic-3, other-test-topic-5]
[INFO ] 2022-02-07 14:56:33.183 [pc-broker-poll]  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=consumer-test-consumer-group-1, groupId=test-consumer-group] (Re-)joining group
[ERROR] 2022-02-07 14:56:33.181 [pc-control]  i.c.p.i.AbstractParallelEoSStreamProcessor - Error from poll control thread, will attempt controlled shutdown, then rethrow. Error: null
java.lang.NullPointerException: null
        at io.confluent.parallelconsumer.state.PartitionMonitor.maybeRaiseHighestSeenOffset(PartitionMonitor.java:226) ~[parallel-consumer-core-0.4.0.2-batching-2.jar!/:?]
        at io.confluent.parallelconsumer.state.PartitionMonitor.maybeRaiseHighestSeenOffset(PartitionMonitor.java:222) ~[parallel-consumer-core-0.4.0.2-batching-2.jar!/:?]
        at io.confluent.parallelconsumer.state.PartitionMonitor.addWorkContainer(PartitionMonitor.java:271) ~[parallel-consumer-core-0.4.0.2-batching-2.jar!/:?]
        at io.confluent.parallelconsumer.state.WorkManager.maybeRegisterNewRecordAsWork(WorkManager.java:209) ~[parallel-consumer-core-0.4.0.2-batching-2.jar!/:?]
        at io.confluent.parallelconsumer.state.WorkManager.ingestPolledRecordsIntoQueues(WorkManager.java:172) ~[parallel-consumer-core-0.4.0.2-batching-2.jar!/:?]
        at io.confluent.parallelconsumer.state.WorkManager.tryToEnsureAvailableCapacity(WorkManager.java:370) ~[parallel-consumer-core-0.4.0.2-batching-2.jar!/:?]
        at io.confluent.parallelconsumer.state.WorkManager.maybeGetWork(WorkManager.java:244) ~[parallel-consumer-core-0.4.0.2-batching-2.jar!/:?]
        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.handleWork(AbstractParallelEoSStreamProcessor.java:664) ~[parallel-consumer-core-0.4.0.2-batching-2.jar!/:?]
        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.controlLoop(AbstractParallelEoSStreamProcessor.java:604) ~[parallel-consumer-core-0.4.0.2-batching-2.jar!/:?]
        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.lambda$supervisorLoop$5(AbstractParallelEoSStreamProcessor.java:565) ~[parallel-consumer-core-0.4.0.2-batching-2.jar!/:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

Note: We have two instances of the ParallelConsumer (with their own KafkaConsumer in the background) as the processing logic from the two topics is slightly different. From the log it's not really clear which message is coming from which ParallelConsumer instance as the thread names are not uniquely generated.

Cheers,
Niels

**Comment by astubbs** [comment]
(And yes, you're correct - unrelated to the batching patch)

**Comment by astubbs** [comment]
FYI Patch available here: https://github.com/confluentinc/parallel-consumer/pull/190

**Comment by astubbs** [comment]
Relates: 
- #200
