### ISSUE TITLE
Does not support Java 16+

### ISSUE THREAD

**Issue by cykl** [confluentinc/parallel-consumer#264]
Using parallel-consumer 0.4.0.1 with Java 17 fails with the following exception at compile time:

``` 
[INFO] Compiling 4 source files to /builds/backend/access-logs-injector/target/classes
An exception has occurred in the compiler (17.0.2). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com/) after checking the Bug Database (http://bugs.java.com/) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
java.util.ServiceConfigurationError: com.sun.source.util.Plugin: Provider com.github.bsideup.jabel.JabelCompilerPlugin could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:220)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.prepareCompiler(JavacTaskImpl.java:204)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:101)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.IllegalAccessError: class com.github.bsideup.jabel.JabelCompilerPlugin (in unnamed module @0x3fbe503c) cannot access class com.sun.tools.javac.code.Source$Feature (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.code to unnamed module @0x3fbe503c
	at com.github.bsideup.jabel.JabelCompilerPlugin.<clinit>(JabelCompilerPlugin.java:26)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	... 34 more
``` 

This is because parallel-consumer uses an old jabel version which doesn't support Java 16+. 0.4.0 seems to fix the issue, see https://github.com/bsideup/jabel/pull/63.

Could you bump jabel version? Six months after Java 17 GA, it would be nice to not have to sprinkle --add-open everywhere ;)

**Comment by cykl** [comment]
Issue might be fixed in master as jabel no longer seems to be a transitive dependency. Still, it would be great to have a release supporting Java 17.

**Comment by astubbs** [comment]
Yeah, it's on the radar.

See:
- #225

And is in the release train:
- #172

Can you try it with master? If not, no worries. I'll also check with tools team about using a 17 base for the Jenkins builds.

**Comment by cykl** [comment]
I did notice #225 and the 1.0, but scope and ETA were unclear to me.

> Can you try it with master?

I will (I want to give the new batching feature a try anyway).

**Comment by cykl** [comment]
Are SNAPSHOT published into a public repository? I gave a look at https://oss.sonatype.org/content/repositories/snapshots/ but failed to find relevant artifacts.

I can install a locally build version into my local repository but it makes integration with CI a bit harder.

**Comment by astubbs** [comment]
No, but give me a couple minutes ;) 
- #265

**Comment by astubbs** [comment]
OK @cykl , it's there: https://oss.sonatype.org/content/repositories/snapshots/io/confluent/parallelconsumer/parallel-consumer-core/0.5.0.0-SNAPSHOT/

**Comment by astubbs** [comment]
FYI I beleive this is resolved now in branch: https://github.com/confluentinc/parallel-consumer/tree/java-17 -build: https://github.com/astubbs/parallel-consumer/pull/2/checks
Can you verify? Can't merge and deploy the snapshot build until our Jenkins is changed.

**Comment by astubbs** [comment]
Thanks everyone, and please vote on your favourite issues! =D

**Comment by astubbs** [comment]
FYI I will do a release this week to get this out there.

**Comment by lopezzlaura** [comment]
Hi, 
Thanks for the quick support 👍  

> truth-generator:0.1-SNAPSHOT is available, and PC is setup to find it.

On the issue with TG, I just tried using PC snapshot (0.5.0.0-SNAPSHOT) and got the following message : `Could not find artifact io.stubbs.truth:truth-generator-api:pom:0.1`, so I guessed the lib wasn't actually published thus can't be found. When I exclude the lib it works fine. I tried again today and still had the same error.

**Comment by astubbs** [comment]
> I just tried using PC snapshot (0.5.0.0-SNAPSHOT) and got the following message : Could not find artifact io.stubbs.truth:truth-generator-api:pom:0.1

By "using", what do you mean exactly? Do you mean using PC in your project as a dependency? Can you email me a full log (antony at confluent)?

**Comment by cykl** [comment]
@lopezzlaura is absent so I'm going to continue. 

I think her issue was that thruth-generator-api is hosted by packagecloud / GitHub package which isn't proxied by our internal Maven repository. While it's fine to host this artifact there and works fine with a vanilla Maven setup, I expect that most organizations don't proxy those Maven repos (yet?) and will have to perform some configuration to use parallel-consumer. Hosting it on more mainstream repos could avoid this extra step.

**Comment by astubbs** [comment]
Ah, proxies! Gotcha.
