### ISSUE TITLE
Message with null key lead to continuous failure when using KEY ordering

### ISSUE THREAD

**Issue by micr0farad** [confluentinc/parallel-consumer#318]
Hey team,
I faced the issue with processing messages which have a null key. I'm using KEY ordering feature and that's obvious why this issue occur, but still it's not safe for consumer to use KEY ordering if one produce a  message with a null key the consumer will not recover. Can we fix that by rather skipping nulls while KEY ordering enabled or by round robing across work queues? 
```
java.lang.NullPointerException: null
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source)
	at io.confluent.parallelconsumer.state.ShardManager.addWorkContainer(ShardManager.java:139)
	at io.confluent.parallelconsumer.state.PartitionStateManager.maybeRegisterNewRecordAsWork(PartitionStateManager.java:361)
	at io.confluent.parallelconsumer.state.PartitionStateManager.maybeRegisterNewRecordAsWork(PartitionStateManager.java:339)
	at io.confluent.parallelconsumer.state.WorkManager.registerWork(WorkManager.java:128)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.processWorkCompleteMailBox(AbstractParallelEoSStreamProcessor.java:953)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.controlLoop(AbstractParallelEoSStreamProcessor.java:671)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.lambda$supervisorLoop$5(AbstractParallelEoSStreamProcessor.java:630)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by astubbs** [comment]
Thanks for your submission! 

Ideally, how would you like to see nulls handled in KEY ordering? Put all null key'd messages into a single queue of equal priority to the other key queues? or a different priority?

This is also closely related to this feature request:
- #183

Seems to me there are probably 2/3 different operating modes for this scenario, of which we could expose as an options.

**Comment by micr0farad** [comment]
@astubbs I think the behavior should be spread across work queues using round robin. This is expected behavior as confluent kafka producer does the same across the partitions. Also I'm curious what was happening in previous release? The issue is not reproducible with 0.4.0.1

**Comment by micr0farad** [comment]
sure, will do

**Comment by micr0farad** [comment]
@astubbs great, was this fix delivered already or what's the plan to deliver?

**Comment by astubbs** [comment]
Not delivered yet - It's at the top of the queue to get merged

**Comment by astubbs** [comment]
However a test that covers what you've described at the ShardManager level would be better, so if you feel so inclined :)

**Comment by astubbs** [comment]
@micr0farad this fix is getting merged now, finally. But it only fixes the issue - null key'd records will all go into one queue and process sequentially.

For parallel processing of null keys, please vote/watch #183
