### ISSUE TITLE
Error during shutdown - ConcurrentModificationException

### ISSUE THREAD

**Issue by JorgenRingen** [confluentinc/parallel-consumer#319]
Only seen this once during close. Should be solved by https://github.com/confluentinc/parallel-consumer/pull/270 according to @astubbs , but posting here in case anyone else get it. 
```
java.util.ConcurrentModificationException: null
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1784) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.LongPipeline.reduce(LongPipeline.java:503) ~[?:?]
	at io.confluent.parallelconsumer.state.PartitionMonitor.getNumberOfEntriesInPartitionQueues(PartitionMonitor.java:258) ~[parallel-consumer-core-0.4.0.1.jar:?]
	at io.confluent.parallelconsumer.state.WorkManager.getNumberOfEntriesInPartitionQueues(WorkManager.java:412) ~[parallel-consumer-core-0.4.0.1.jar:?]
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.controlLoop(AbstractParallelEoSStreamProcessor.java:650) ~[parallel-consumer-core-0.4.0.1.jar:?]
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.lambda$supervisorLoop$5(AbstractParallelEoSStreamProcessor.java:563) ~[parallel-consumer-core-0.4.0.1.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
```

**Comment by johnbyrnejb** [comment]
Closing Issue
