### ISSUE TITLE
Is There Any Exception Handler?

### ISSUE THREAD

**Issue by 10000-ki** [confluentinc/parallel-consumer#550]
If an error occurs while the conuser polls the message
example deserialize exception

```
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing key/value for partition crash-android-21 at offset 1047530996. If needed, please seek past the record to continue consumption.
  at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
  at java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[?:?]
  at io.confluent.parallelconsumer.internal.BrokerPollSystem.closeAndWait(BrokerPollSystem.java:247) ~[parallel-consumer-core-0.5.2.3.jar:?]
  at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.doClose(AbstractParallelEoSStreamProcessor.java:529) ~[parallel-consumer-core-0.5.2.3.jar:?]
  at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.lambda$supervisorLoop$5(AbstractParallelEoSStreamProcessor.java:665) ~[parallel-consumer-core-0.5.2.3.jar:?]
  at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
  at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.apache.kafka.common.errors.RecordDeserializationException: Error deserializing key/value for partition crash-android-21 at offset 1047530996. If needed, please seek past the record to continue consumption.
  at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1435) ~[kafka-clients-3.3.1.jar:?]
  at org.apache.kafka.clients.consumer.internals.Fetcher.access$3400(Fetcher.java:133) ~[kafka-clients-3.3.1.jar:?]
  at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1658) ~[kafka-clients-3.3.1.jar:?]
  at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1900(Fetcher.java:1494) ~[kafka-clients-3.3.1.jar:?]
  at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:716) ~[kafka-clients-3.3.1.jar:?]
  at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:682) ~[kafka-clients-3.3.1.jar:?]
  at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1291) ~[kafka-clients-3.3.1.jar:?]
  at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1247) ~[kafka-clients-3.3.1.jar:?]
  at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1220) ~[kafka-clients-3.3.1.jar:?]
  at io.confluent.parallelconsumer.internal.ConsumerManager.poll(ConsumerManager.java:54) ~[parallel-consumer-core-0.5.2.3.jar:?]
  at io.confluent.parallelconsumer.internal.BrokerPollSystem.pollBrokerForRecords(BrokerPollSystem.java:183) ~[parallel-consumer-core-0.5.2.3.jar:?]
  at io.confluent.parallelconsumer.internal.BrokerPollSystem.handlePoll(BrokerPollSystem.java:140) ~[parallel-consumer-core-0.5.2.3.jar:?]
  at io.confluent.parallelconsumer.internal.BrokerPollSystem.controlLoop(BrokerPollSystem.java:116) ~[parallel-consumer-core-0.5.2.3.jar:?]
  ... 4 more
Caused by: java.lang.IllegalArgumentException: Location must not be null
```

the polling thread die. And after that, it doesn't work normally.

is there any exception handler like apache kafka 

```
ConcurrentKafkaListenerContainerFactory<>();
  configurer.configure(factory, kafkaConsumerFactory);
  factory.setErrorHandler(new SeekToCurrentErrorHandler());
```

like this

**Comment by rkolesnev** [comment]
Hi,

As far as i know there is no additional error handling in Parallel Consumer for errors stemming from Kafka Consumer poll calls - like the deserialization exception above.

The Apache Kafka consumer doesn't have standard exception handlers for this scenario - the example above using ConcurrentKafkaListenerContainerFactory is from the Spring Framework.

**Comment by 10000-ki** [comment]
I wonder if there is a plan to add error handler processing or if we need to customize it.

**Comment by rkolesnev** [comment]
I believe there is - eventually - it makes sense to add it. 
But i dont have any specific time frame for it.

Here are couple of related issues - https://github.com/confluentinc/parallel-consumer/issues/195 and https://github.com/confluentinc/parallel-consumer/issues/304. 

#304 suggests an one of the options to get around it - defer deserialization to the user function - Consume as byte[],byte[] and handle deserialization and exceptions yourself - there you can either skip failed message or implement DLQ etc... as opposed to wrapping Consumer and handling exceptions on poll().

**Comment by colinkuo** [comment]
https://developer.confluent.io/courses/kafka-streams/hands-on-error-handling/
Borrowing the idea from `ProductionExceptionHandler` of Kafka Streams also looks good. Just let users to decide either fail the processing or ignore the problematic messages

**Comment by astubbs** [comment]
Tracked in the maintained fork as astubbs/parallel-consumer#163, which carries a summary of this
issue and its current status there.

The **Confluent-hosted version** of this project is no longer maintained - its README says so.
**Parallel Consumer itself continues** in my fork: https://github.com/astubbs/parallel-consumer

Nothing in this repository is closed or changed by this comment.

**Comment by astubbs** [comment]
@10000-ki, @colinkuo - the answer from the maintained fork, late but with a plan that is code rather than an intention:

- **Today, no.** The classic API has no handler for a `RecordDeserializationException` out of `consumer.poll()`, still true in the fork's [v0.6.0.0](https://github.com/astubbs/parallel-consumer/releases/tag/v0.6.0.0). The broker-poll thread dies, the instance closes and leaves the group, and the cause is reachable through `getFailureCause()`. Retry-with-delay and skip live on the processing path, on a record already deserialised, so they cannot apply.
- **Workaround on the classic API.** Consume as `byte[]/byte[]`, deserialise inside the processing function, and handle the failure there - skip, divert, or rethrow to retry. One caveat: on the processing path a throw is retried with no ceiling, so "give up" means catching it and returning normally.
- **The answer being built: the fluent API** (astubbs/parallel-consumer#504, in review as astubbs/parallel-consumer#502). A route declares its consumed format and decoding runs inside the function's attempt on the raw bytes, so a decode failure never reaches the poll thread; it reports as permanent or transient, transient retries, and permanent goes to the route's after-retries reaction, park in place by default. That is the handler in the shape @colinkuo pointed at, minus a callback interface: the decision is an outcome the function returns.
- **The classic API's own poll seam** stays tracked as astubbs/parallel-consumer#148 (stop a bad record killing the poll thread) and astubbs/parallel-consumer#153 (a policy API), and whether the classic API gains it is a later question.

Mirror: astubbs/parallel-consumer#163.
