### ISSUE TITLE
Consumer hangs while polling

### ISSUE THREAD

**Issue by shaileshkulkarni** [confluentinc/parallel-consumer#576]
The consumer configuration
var options = ParallelConsumerOptions.<String, GenericRecord>builder()
            .ordering(KEY)
            .maxConcurrency(100)
            .consumer(getKafkaConsumer())
            .commitMode(CommitMode.PERIODIC_CONSUMER_ASYNCHRONOUS)
            .commitInterval(Duration.ofMillis(2000))
            .offsetCommitTimeout(Duration.ofMillis(5000))
            .build();

        ParallelEoSStreamProcessor<String, GenericRecord> parallelStreamProcessor =
            (ParallelEoSStreamProcessor) ParallelStreamProcessor.createEosStreamProcessor(options);

        LOG.debug("{}, subscribing to topics {}", methodName, subscribedTopics);
        parallelStreamProcessor.subscribe(subscribedTopics, partitionRebalancerListener);
------------
private TracingKafkaConsumer<String, GenericRecord> getKafkaConsumer() {

        Properties props = new Properties();        
        props.setProperty(ConsumerConfig.GROUP_ID_CONFIG, groupName);
        props.setProperty(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, "false");
        props.setProperty(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "latest");

        org.apache.kafka.clients.consumer.Consumer<String, GenericRecord> regularConsumer = new KafkaConsumer<>(
            props, new ErrorHandlingDeserializer<>(new StringDeserializer()), avroValueDeserializer);
        return new TracingKafkaConsumer<>(regularConsumer, tracer);
    }
---------------
Seen issue when the lamda function which does some I/O operation took around 15 seconds to respond back due to IO activity timeout (socket timeout) then there was no further polling to kafka from all the threads and it seems that the consumer has hanged.

The this.parallelConsumer.isClosedOrFailed() when tried to check from external thread is returning false but there is no actual event polling happening with Kafka.

at somepackage.KafkaParallelConsumer.lambda$poll$1(KafkaParallelConsumer.java:96)
	at io.confluent.parallelconsumer.internal.UserFunctions.carefullyRun(UserFunctions.java:61)
	at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.lambda$poll$0(ParallelEoSStreamProcessor.java:54)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.runUserFunctionInternal(AbstractParallelEoSStreamProcessor.java:1219)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.runUserFunction(AbstractParallelEoSStreamProcessor.java:1170)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.lambda$submitWorkToPoolInner$9(AbstractParallelEoSStreamProcessor.java:828)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

----------------
I checked the source code of ParallelEosStreamProcessor, the supervisior loop will not get called immediately if the consumer function takes long time. 

public void poll(Consumer<PollContext<K, V>> usersVoidConsumptionFunction) {
        Function<PollContextInternal<K, V>, List<Object>> wrappedUserFunc = (context) -> {
            log.trace("asyncPoll - Consumed a consumerRecord ({}), executing void function...", context);
            UserFunctions.carefullyRun(usersVoidConsumptionFunction, context.getPollContext());
            log.trace("asyncPoll - user function finished ok.");
            return UniLists.of();
        };
        Consumer<Object> voidCallBack = (ignore) -> {
            log.trace("Void callback applied.");
        };
        this.supervisorLoop(wrappedUserFunc, voidCallBack);
    }

**Comment by shaileshkulkarni** [comment]
I have concluded based on wrong set of logs. Please ignore this issue.
