### ISSUE TITLE
Error while shutting down parallel consumers in 0.5.2.6

### ISSUE THREAD

**Issue by antonmos** [confluentinc/parallel-consumer#617]
```
2023-08-03T14:40:21.199-05:00 ERROR 6546 --- [onPool-worker-2] c.p.i.AbstractParallelEoSStreamProcessor : Execution or timeout exception while waiting for the control thread to close cleanly (state was CLOSING). Try increasing your time-out to allow the system to drain, or close without draining.

java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[na:na]
        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.waitForClose(AbstractParallelEoSStreamProcessor.java:557) ~[parallel-consumer-core-0.5.2.6.jar:na]
        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.close(AbstractParallelEoSStreamProcessor.java:537) ~[parallel-consumer-core-0.5.2.6.jar:na]
        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.close(AbstractParallelEoSStreamProcessor.java:516) ~[parallel-consumer-core-0.5.2.6.jar:na]
        at io.confluent.parallelconsumer.internal.DrainingCloseable.closeDontDrainFirst(DrainingCloseable.java:61) ~[parallel-consumer-core-0.5.2.6.jar:na]
        at com.oppfi.dddfeatures.kafka.services.KafkaParallelConsumerImpl.stop(KafkaParallelConsumerImpl.java:113) ~[ddd-base-features-1.0.4-SNAPSHOT.jar:1.0.4-SNAPSHOT]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[na:na]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "key" is null
        at java.base/java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936) ~[na:na]
        at io.micrometer.core.instrument.MeterRegistry.remove(MeterRegistry.java:698) ~[micrometer-core-1.11.1.jar:1.11.1]
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
        at io.confluent.parallelconsumer.metrics.PCMetrics.close(PCMetrics.java:176) ~[parallel-consumer-core-0.5.2.6.jar:na]
        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.doClose(AbstractParallelEoSStreamProcessor.java:629) ~[parallel-consumer-core-0.5.2.6.jar:na]
        at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.lambda$supervisorLoop$10(AbstractParallelEoSStreamProcessor.java:741) ~[parallel-consumer-core-0.5.2.6.jar:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

```

**Comment by rkolesnev** [comment]
Hi @antonmos - can you provide reproduceable steps / setup that results in this error, please?

**Comment by antonmos** [comment]
This happened in our test suite. I will try to isolate it but I am not sure I will have time for this soon.

**Comment by JorgenRingen** [comment]
We're actually getting exception on shutdown as well consistently on 0.5.2.6 in applications.

```
Error from poll control thread, will attempt controlled shutdown, then rethrow. Error: null

java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:204) ~[?:?]
	at io.confluent.parallelconsumer.internal.BrokerPollSystem.closeAndWait(BrokerPollSystem.java:274) ~[parallel-consumer-core-0.5.2.6.jar:?]
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.doClose(AbstractParallelEoSStreamProcessor.java:624) ~[parallel-consumer-core-0.5.2.6.jar:?]
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.controlLoop(AbstractParallelEoSStreamProcessor.java:791) ~[parallel-consumer-core-0.5.2.6.jar:?]
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.lambda$supervisorLoop$10(AbstractParallelEoSStreamProcessor.java:730) ~[parallel-consumer-core-0.5.2.6.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

```
pc.closeDrainFirst(Duration.ofSeconds(25))
```

**Comment by dannpopescu** [comment]
I've also seen an exception on shutdown in one of my tests. Only once, so no steps to reproduce.

```
i.c.p.i.AbstractParallelEoSStreamProcessor - Error from poll control thread, will attempt controlled shutdown, then rethrow. Error: null
java.util.ConcurrentModificationException: null
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1513)
	at io.confluent.parallelconsumer.metrics.PCMetrics.close(PCMetrics.java:176)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.doClose(AbstractParallelEoSStreamProcessor.java:629)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.controlLoop(AbstractParallelEoSStreamProcessor.java:791)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.lambda$supervisorLoop$10(AbstractParallelEoSStreamProcessor.java:730)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by antonmos** [comment]
yes, i am seeing it on shutdown every time now.

**Comment by antonmos** [comment]
I have 10 PCs running and we are shutting them down in parallel. I am guessing there is a race condition during shutdown.

**Comment by antonmos** [comment]
I think i see the problem.
PCMetrics is a singleton. 
AbstractParallelEoSStreamProcessor.doClose calls PCMetrics.close(), which does

```
        instance.registeredMeters.forEach(registry::remove);
        instance.registeredMeters.clear();
```

Instance.registeredMeters is an ArrayList which is not thread-safe.
So, so when multiple threads are iterating and one calls `clear`, the other threads encounter nulls.

**Comment by antonmos** [comment]
I think making PCMetrics.close() `synchronized` would fix this, and it makes sense because PCMetrics is a singleton, so only one thread should close it, and the result will wait then will exit quickly in
``` 
if (instance == null) {
            return;
        }
```

**Comment by rkolesnev** [comment]
Hi @antonmos,

I think there is a potential for race condition between closing down PCMetrics and unsubscribing partitions - which removes individual meters during shutdown phase as well - so synchronised lock between PCMetrics remove meter and close methods might be the solution (plus null checks for defensive access).

I am on holidays now - but will be back at work next week and will look into it.

For PCMetrics being singleton - do you run multiple PC instances in same java process? Is it effectively shared between multiple PC instances in your use case?

If the above is the case - I think we might need to make sure it's isolated per PC instance - refactor away static instance/accessors - as otherwise there may be meter collisions and unintended behaviour.

**Comment by antonmos** [comment]
> For PCMetrics being singleton - do you run multiple PC instances in same java process? Is it effectively shared between multiple PC instances in your use case?

that's right.  yes, ideally, metrics would be separate by PC instance.

I'd like to propose that you make a quick fix first, to prevent the error on shutdown and then proceed with the the refactoring.
Currently, our tests and shutdowns are delayed because spring waits for 30s when this error happens.

Thank you for your time!

**Comment by antonmos** [comment]
FWIW, the change in my PR fixes the error and tests are passing.

**Comment by cykl** [comment]
> that's right. yes, ideally, metrics would be separate by PC instance.

I agree. PC instances should be named (or accept key-value tag) and each PC instance should publish distinct metrics.
