### ISSUE TITLE
Interrupted exception during shutdown

### ISSUE THREAD

**Issue by JorgenRingen** [confluentinc/parallel-consumer#668]
During shutdown we sometimes get the following exception:
```
Exception caught in user function running stage, registering WC as failed, returning to mailbox. Context: PollContextInternal(pollContext=PollContext .... )
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1081) ~[?:?]
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:276) ~[?:?]
	at org.apache.kafka.clients.producer.internals.ProduceRequestResult.await(ProduceRequestResult.java:86) ~[kafka-clients-3.5.0.jar:?]
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:74) ~[kafka-clients-3.5.0.jar:?]
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:30) ~[kafka-clients-3.5.0.jar:?]
	at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.lambda$processAndProduceResults$3(ParallelEoSStreamProcessor.java:128) ~[parallel-consumer-core-0.5.2.5.jar:?]
	at io.confluent.csid.utils.TimeUtils.timeWithMeta(TimeUtils.java:34) ~[parallel-consumer-core-0.5.2.5.jar:?]
	at io.confluent.csid.utils.TimeUtils.time(TimeUtils.java:27) ~[parallel-consumer-core-0.5.2.5.jar:?]
	at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.processAndProduceResults(ParallelEoSStreamProcessor.java:124) ~[parallel-consumer-core-0.5.2.5.jar:?]
```

Using commit-mode periodic-consumer-sync and `pc.closeDrainFirst(Duration.ofSeconds(25))` to shutdown.

**Comment by rkolesnev** [comment]
That may be the case if the duration given for shut down is exceeded - i believe there should be more logs about it - those messages will be treated as failed and not committed - so that they can be replayed after re-balance.
the default Drain period timeout is 30 seconds - it can be overridden through ParallelConsumerOptions drainTimeout config.
Generally shutdown process has 3 timeouts:
1) Primary shutdownTimeout - that is the timeout specified in close(Duration) method - alternatively it can be set through ParallelConsumerOptions.shutdownTimeout (default 10 seconds) for using close() / closeDrainFirst() overloads.
2) drainTimeout - additional timeout for closeDrainFirst - can be set through ParallelConsumerOptions.drainTimeout (default 30 seconds)
3) Fixed grace period of 10 seconds for forced threadpool shutdown if graceful drain / inflight processing timedout.

That approach is mostly to support separate timeouts for graceful shutdown with draining vs shutdown on error (without draining) - as it may be desirable to have long timeout in drain mode only.

**Comment by rkolesnev** [comment]
So for the closeDrainFirst(Duration.ofSeconds(25)) - it will be 55 seconds for drain + shutdown and 10 more seconds for handing cleanup on graceful shutdown timing out.
So i would expect those interrupted exceptions to be logged roughly 55-65 seconds after shutdown initiation.

**Comment by JorgenRingen** [comment]
We're doing grpc calls in the user-function. After some investigation, I noticed that spring, which handles shutdown of the app, automatically closes grpc during shutdown. Rewritten to only "manual shutdown" of grpc after PC has successfully closed. Hopefully this will solve the issue 🤞

**Comment by rkolesnev** [comment]
yeah - sounds plausible :) - if closed GRPC resulted in user function blocking on grpc call or looping on retry of grpc call - that would cause drain to timeout and forcibly interrupt threads to force completion. Basically its to prevent PC to get stuck in drain mode for too long.

Closing - please reopen if new details emerge pointing to issue with PC logic.
