### ISSUE TITLE
The ParallelStreamProcessor closing problem

### ISSUE THREAD

**Issue by Satrix** [confluentinc/parallel-consumer#685]
Hey guys,

First of all thanks for creating that library - it's really good!

We are trying to use that in our microservices and lately during our integration testing we've discovered that the ParallelStreamProcessor fails to close properly in which case the KafkaConsumer is still somehow attached to the topic's partition - up until it times out and Kafka cluster removes that KafkaConsumer from consumer group. The interesting fact is that there are no new messages incoming so the shutdown should be pretty quick but instead it looks like it's hanging in a loop.
It seems like the problem occurs once we start adding more ParallelStreamProcessors in our code. To make it even more complicated the behaviour is kind of a flaky because sometimes all the streams are closed properly and sometimes they fail (non deterministic).

Below you can find the code to reproduce the problem:
```
        ParallelEoSStreamProcessor<String, byte[]> mainStream = newStream();
        ParallelEoSStreamProcessor<String, byte[]> retryStream = newStream();
        ParallelEoSStreamProcessor<String, byte[]> dlqStream = newStream();

        String message = "a-message";
        kafkaSender.send(TOPIC, message);
        kafkaSender.send(RETRY_TOPIC, message);
        kafkaSender.send(DEAD_LETTER_TOPIC, message);

        mainStream.subscribe(Collections.singleton(TOPIC));
        mainStream.pollAndProduceMany(ctx -> Collections.emptyList());

        retryStream.subscribe(Collections.singleton(RETRY_TOPIC));
        retryStream.pollAndProduceMany(ctx -> Collections.emptyList());

        dlqStream.subscribe(Collections.singleton(DEAD_LETTER_TOPIC));
        dlqStream.pollAndProduceMany(ctx -> Collections.emptyList());

        Thread.sleep(3000L);

        mainStream.close();
        retryStream.close();
        dlqStream.close();
```
This is how we create our ParallelStreamProcessors:
```
private ParallelEoSStreamProcessor<String, byte[]> newStream() {
        Map<String, Object> producerConfig = KafkaFactory.createProducerConfig(kafkaContainer);
        Map<String, Object> consumerConfig = KafkaFactory.createConsumerConfig(CONSUMER_GROUP_ID, kafkaContainer);

        ParallelConsumerOptions<String, byte[]> options = ParallelConsumerOptions.builder()
                        .ordering(ParallelConsumerOptions.ProcessingOrder.UNORDERED)
                        .consumer(new KafkaConsumer<>(consumerConfig))
                        .producer(new KafkaProducer<>(producerConfig))
                        .shutdownTimeout(Duration.ofSeconds(70))
                        .build();

        return new ParallelEoSStreamProcessor(options);
    }
```

This is our simple test to reproduce the problem. As you can see we have three ParallelEoSStreamProcessors for three different topics. As a next step we try to send one message to each topic. Once it's done we start to consume from those topics. After 3 seconds we are trying to close the streams and that's where we get the following stacktrace:

```
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Mailbox results returned null, indicating timeToBlockFor elapsed (which was set as PT5S)
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- isPoolQueueLow()? workAmountBelowTarget true 0 vs 16;
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Stats: 
- pool active: 0 queued:0 
- queue size: 0 target: 16 loading factor: 2
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Starting close process (state: CLOSING)...
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.BrokerPollSystem -- Signaling poll system to drain, waking up consumer...
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.ConsumerManager -- Waking up consumer
16:27:28.175 [pc-control] DEBUG org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient -- [Consumer clientId=consumer-a-consumer-group-3, groupId=a-consumer-group] Received user wakeup
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Shutting down execution pool...
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Awaiting worker pool termination...
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Still awaiting completion of inflight work
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Worker pool terminated.
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Committing offsets that are ready...
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.ConsumerOffsetCommitter -- Async commit to be requested
16:27:28.175 [pc-broker-poll] DEBUG org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient -- [Consumer clientId=consumer-a-consumer-group-3, groupId=a-consumer-group] Raising WakeupException in response to user wakeup
16:27:28.175 [pc-broker-poll] DEBUG io.confluent.parallelconsumer.internal.ConsumerManager -- Awoken from broker poll
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.ConsumerManager -- Waking up consumer
16:27:28.175 [pc-control] DEBUG org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient -- [Consumer clientId=consumer-a-consumer-group-3, groupId=a-consumer-group] Received user wakeup
16:27:28.175 [pc-broker-poll] DEBUG io.confluent.parallelconsumer.internal.BrokerPollSystem -- Poll completed
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Closing and waiting for broker poll system...
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.BrokerPollSystem -- Requesting broker polling system to close...
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.BrokerPollSystem -- Poller transitioning to closing, waking up consumer
16:27:28.175 [pc-control] DEBUG io.confluent.parallelconsumer.internal.BrokerPollSystem -- Wait for loop to finish ending...
16:27:28.175 [pc-broker-poll] DEBUG io.confluent.parallelconsumer.internal.BrokerPollSystem -- Got 0 records in poll result
16:27:28.175 [pc-broker-poll] DEBUG io.confluent.parallelconsumer.internal.ConsumerOffsetCommitter -- Commit requested, performing...
16:27:28.175 [pc-broker-poll] DEBUG io.confluent.parallelconsumer.internal.AbstractOffsetCommitter -- Find completed work to commit offsets
16:27:28.176 [pc-broker-poll] DEBUG io.confluent.parallelconsumer.internal.AbstractOffsetCommitter -- No offsets ready
16:27:28.176 [pc-broker-poll] DEBUG io.confluent.parallelconsumer.internal.BrokerPollSystem -- Doing close...
16:27:28.176 [pc-broker-poll] DEBUG io.confluent.parallelconsumer.internal.BrokerPollSystem -- Pausing subs
16:27:28.176 [pc-broker-poll] DEBUG org.apache.kafka.clients.consumer.KafkaConsumer -- [Consumer clientId=consumer-a-consumer-group-3, groupId=a-consumer-group] Pausing partitions [topic.dlt-0]
16:27:28.176 [pc-broker-poll] DEBUG io.confluent.parallelconsumer.internal.BrokerPollSystem -- Closing BrokerPollSystem, first closing consumer...
16:27:28.176 [kafka-coordinator-heartbeat-thread | a-consumer-group] DEBUG org.apache.kafka.clients.consumer.internals.ConsumerCoordinator -- [Consumer clientId=consumer-a-consumer-group-3, groupId=a-consumer-group] Heartbeat thread has closed
16:27:28.176 [pc-broker-poll] DEBUG org.apache.kafka.clients.consumer.internals.ConsumerCoordinator -- [Consumer clientId=consumer-a-consumer-group-3, groupId=a-consumer-group] Executing onLeavePrepare with generation Generation{generationId=2, memberId='consumer-a-consumer-group-3-747f48f8-1c32-4cae-ac4d-4ac465e828e9', protocol='range'}
16:27:28.176 [pc-broker-poll] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator -- [Consumer clientId=consumer-a-consumer-group-3, groupId=a-consumer-group] Revoke previously assigned partitions topic.dlt-0
16:27:28.176 [pc-broker-poll] INFO org.apache.kafka.clients.consumer.internals.ConsumerCoordinator -- [Consumer clientId=consumer-a-consumer-group-3, groupId=a-consumer-group] The pause flag in partitions [topic.dlt-0] will be removed due to revocation.
16:27:28.176 [pc-broker-poll] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Partitions revoked [topic.dlt-0], state: CLOSING
16:27:58.180 [pc-control] ERROR io.confluent.parallelconsumer.internal.BrokerPollSystem -- Execution or timeout exception waiting for broker poller thread to finish
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at io.confluent.parallelconsumer.internal.BrokerPollSystem.closeAndWait(BrokerPollSystem.java:277)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.doClose(AbstractParallelEoSStreamProcessor.java:626)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.controlLoop(AbstractParallelEoSStreamProcessor.java:801)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.lambda$supervisorLoop$10(AbstractParallelEoSStreamProcessor.java:740)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
16:27:58.180 [pc-control] ERROR io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Error from poll control thread, will attempt controlled shutdown, then rethrow. Error: null
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at io.confluent.parallelconsumer.internal.BrokerPollSystem.closeAndWait(BrokerPollSystem.java:277)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.doClose(AbstractParallelEoSStreamProcessor.java:626)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.controlLoop(AbstractParallelEoSStreamProcessor.java:801)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.lambda$supervisorLoop$10(AbstractParallelEoSStreamProcessor.java:740)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
16:27:58.180 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Starting close process (state: CLOSING)...
16:27:58.180 [pc-control] DEBUG io.confluent.parallelconsumer.internal.BrokerPollSystem -- Signaling poll system to drain, waking up consumer...
16:27:58.180 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Shutting down execution pool...
16:27:58.180 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Awaiting worker pool termination...
16:27:58.180 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Still awaiting completion of inflight work
16:27:58.180 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Worker pool terminated.
16:27:58.180 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Committing offsets that are ready...
16:27:58.180 [pc-control] DEBUG io.confluent.parallelconsumer.internal.ConsumerOffsetCommitter -- Async commit to be requested
16:27:58.181 [pc-control] DEBUG io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Closing and waiting for broker poll system...
16:27:58.181 [pc-control] DEBUG io.confluent.parallelconsumer.internal.BrokerPollSystem -- Requesting broker polling system to close...
16:27:58.181 [pc-control] DEBUG io.confluent.parallelconsumer.internal.BrokerPollSystem -- Poller transitioning to closing, waking up consumer
16:27:58.181 [pc-control] DEBUG io.confluent.parallelconsumer.internal.BrokerPollSystem -- Wait for loop to finish ending...
16:28:28.185 [pc-control] ERROR io.confluent.parallelconsumer.internal.BrokerPollSystem -- Execution or timeout exception waiting for broker poller thread to finish
java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at io.confluent.parallelconsumer.internal.BrokerPollSystem.closeAndWait(BrokerPollSystem.java:277)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.doClose(AbstractParallelEoSStreamProcessor.java:626)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.lambda$supervisorLoop$10(AbstractParallelEoSStreamProcessor.java:751)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

16:28:28.186 [Test worker] ERROR io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor -- Execution or timeout exception while waiting for the control thread to close cleanly (state was CLOSING). Try increasing your time-out to allow the system to drain, or close without draining.
java.util.concurrent.ExecutionException: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.waitForClose(AbstractParallelEoSStreamProcessor.java:559)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.close(AbstractParallelEoSStreamProcessor.java:539)
	at io.confluent.parallelconsumer.internal.DrainingCloseable.closeDontDrainFirst(DrainingCloseable.java:47)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.close(AbstractParallelEoSStreamProcessor.java:512)
	at com.example.kafka.consumer.DefaultKafkaParallelConsumerIT.test(DefaultKafkaParallelConsumerIT.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:110)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:85)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: java.util.concurrent.TimeoutException: null
	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
	at io.confluent.parallelconsumer.internal.BrokerPollSystem.closeAndWait(BrokerPollSystem.java:277)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.doClose(AbstractParallelEoSStreamProcessor.java:626)
	at io.confluent.parallelconsumer.internal.AbstractParallelEoSStreamProcessor.lambda$supervisorLoop$10(AbstractParallelEoSStreamProcessor.java:751)
```

We've tried to close the streams without draining, with draining, changing the shutdown timeout but nothing helps.
I look forward to hearing from you guys - we really want to use your lib but it's a critical blocker for us now.
Thanks in advance.

**Comment by Satrix** [comment]
I will try to take a look tommorow at https://github.com/confluentinc/parallel-consumer/issues/648 because it may be the issue in our case as well.

**Comment by Satrix** [comment]
Ok, I can confirm that the problem disappeared once I removed the KafkaProducer that wasn't transactional.

Are there any plans to release a new version that fixes that issue? (https://github.com/confluentinc/parallel-consumer/issues/648)

**Comment by rkolesnev** [comment]
Hi @Satrix - i am doing the release today. 
Can you please test the behaviour with the new version - once it is released - to confirm that the fix for the (#648) indeed resolved this behaviour and update the issue here with results?

**Comment by Satrix** [comment]
Yes, no worries. I will test that tommorow with the new version 👍

**Comment by rkolesnev** [comment]
@Satrix - can you double check? clear caches etc - i can see it on repo1 - https://repo1.maven.org/maven2/io/confluent/parallelconsumer/parallel-consumer-core/0.5.2.8/

**Comment by Satrix** [comment]
I was looking for the artifact here: https://mvnrepository.com/artifact/io.confluent.parallelconsumer/parallel-consumer-core

**Comment by rkolesnev** [comment]
@Satrix - mvnrepository is unofficial maven mirror afaik - it is outside of my hands how fast they replicate from repo1.
https://central.sonatype.org/faq/mvnrepository/

**Comment by Satrix** [comment]
@rkolesnev - I've tested the newest release and it seems like it's working fine with the fix in place. Thanks 🙇 

I'm gonna close the issue then.
