### ISSUE TITLE
UniJ issue #55 UnsupportedClassVersion

### ISSUE THREAD

**Issue by rakrak98** [confluentinc/parallel-consumer#87]
Hello! I am trying to run the parallel consumer library (https://github.com/confluentinc/parallel-consumer) and I seem to be getting the following error. Anyone know why?
ERROR    2021-03-16 16:23:00,133    0    io.confluent.parallelconsumer.BrokerPollSystem    [control]    Execution or timeout exception waiting for broker poller thread to finish
java.util.concurrent.ExecutionException: java.lang.UnsupportedClassVersionError: pl/tlinkowski/unij/service/collect/jdk8/Jdk8UnmodifiableMapFactory has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:206)
    at io.confluent.parallelconsumer.BrokerPollSystem.closeAndWait(BrokerPollSystem.java:205)
    at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.doClose(ParallelEoSStreamProcessor.java:420)
    at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.controlLoop(ParallelEoSStreamProcessor.java:601)
    at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.lambda$supervisorLoop$10(ParallelEoSStreamProcessor.java:544)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedClassVersionError: pl/tlinkowski/unij/service/collect/jdk8/Jdk8UnmodifiableMapFactory has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
    at java.lang.Iterable.forEach(Iterable.java:74)
    at pl.tlinkowski.unij.api.UniJLoader.load(UniJLoader.java:42)
    at pl.tlinkowski.unij.api.UniJ.mapFactory(UniJ.java:36)
    at pl.tlinkowski.unij.api.UniMaps.of(UniMaps.java:71)
    at io.confluent.parallelconsumer.ConsumerManager.poll(ConsumerManager.java:39)
    at io.confluent.parallelconsumer.BrokerPollSystem.pollBrokerForRecords(BrokerPollSystem.java:169)
    at io.confluent.parallelconsumer.BrokerPollSystem.controlLoop(BrokerPollSystem.java:102)

**Comment by astubbs** [comment]
Are you using Java 8?

**Comment by rakrak98** [comment]
> Are you using Java 8?

Yes! I am using Java8, more specifically, corretto-1.8.0_282

**Comment by astubbs** [comment]
This is a known issue with java 8 with one of the dependencies, which has apparently now been fixed. I need to upgrade to it's latest version and cut a release. For now, you could try pulling it in yourself: 
https://github.com/tlinkowski/UniJ/issues/55#issuecomment-769182766

Force your project to pull in 0.1.3

        <dependency>
            <groupId>pl.tlinkowski.unij</groupId>
            <artifactId>pl.tlinkowski.unij.api</artifactId>
            <version>0.1.3</version>
        </dependency>
        <dependency>
            <groupId>pl.tlinkowski.unij</groupId>
            <artifactId>pl.tlinkowski.unij.bundle.jdk8</artifactId>
            <version>0.1.3</version>
            <scope>compile</scope>
        </dependency>

**Comment by rakrak98** [comment]
Thanks! I tried to put those dependencies in my project, and this is the new error I got:

ERROR	2021-03-16 17:18:30,970	0	io.confluent.parallelconsumer.BrokerPollSystem	[control]	Execution or timeout exception waiting for broker poller thread to finish
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: pl/tlinkowski/unij/api/UniMaps
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at io.confluent.parallelconsumer.BrokerPollSystem.closeAndWait(BrokerPollSystem.java:205)
	at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.doClose(ParallelEoSStreamProcessor.java:420)
	at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.controlLoop(ParallelEoSStreamProcessor.java:601)
	at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.lambda$supervisorLoop$10(ParallelEoSStreamProcessor.java:544)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: pl/tlinkowski/unij/api/UniMaps
	at io.confluent.parallelconsumer.ConsumerManager.poll(ConsumerManager.java:39)
	at io.confluent.parallelconsumer.BrokerPollSystem.pollBrokerForRecords(BrokerPollSystem.java:169)
	at io.confluent.parallelconsumer.BrokerPollSystem.controlLoop(BrokerPollSystem.java:102)
	... 4 more

**Comment by astubbs** [comment]
Weird. I have done the upgrade locally, all seems fine. I'm going to enable the JDK 8 tests again, and push the PR. You can then pull down that snapshot and install it locally, while waiting for the build to publish.

**Comment by rakrak98** [comment]
> Weird. I have done the upgrade locally, all seems fine. I'm going to enable the JDK 8 tests again, and push the PR. You can then pull down that snapshot and install it locally, while waiting for the build to publish.

I actually had to re-start my IDE and mvn clean install, and the error ended up going away. However, the consumer itself is not joining my local kafka cluster. The kafka cluster is not detecting the consumer for some reason. Maybe using the snapshot would help.

**Comment by astubbs** [comment]
Can you link a minimal example reproducing the issue? Or at least sample code?

**Comment by astubbs** [comment]
> I left the breakpoint at the lambda expression in the poll() function, and it never reaches that point for some reason. Also, none of the messages that I am sending via the producer are being processed by the consumer.

I think, as in the other issue you opened, you are closing the PC immediately after calling `#poll`. The various poll functions don't block, they execute asynchronously. You can either use another event to signal `close` to run, or do something like capture ctrl-c from the keyboard.
