### ISSUE TITLE
Unable to consume messages from a topic

### ISSUE THREAD

**Issue by mroiter-larus** [confluentinc/parallel-consumer#96]
Hi,

i'm just testing the library, but i'm not able to consume any message from my topic.
I created a topic named `parallelConsumerTest`, with 10 partitions, and produced 1 million records in it. I already checked that the topic is not empty.

Here is my Java consumer:

```
Consumer<String, String> consumer = ConsumerCreator.createParallelConsumer();

ParallelConsumerOptions<String, String> options = ParallelConsumerOptions.<String, String>builder()
		.consumer(consumer)
		.ordering(ParallelConsumerOptions.ProcessingOrder.PARTITION)
		.maxConcurrency(10)
		.build();

ParallelStreamProcessor<String, String> parallelConsumer = ParallelStreamProcessor.createEosStreamProcessor(options);
parallelConsumer.subscribe(Collections.singletonList("parallelConsumerTest"));

System.out.println("PARALLEL CONSUMER SUBSCRIBED");
Map<String, String> mapRecord = new HashMap<>();

parallelConsumer.poll(record -> {

	System.out.println("Concurrently processing a record: {}" + record);
	mapRecord.put(record.key(), record.value());
});

System.out.println("RECORD COUNT: " + mapRecord.size());
```

What happen is that my `mapRecord` is always empty and i can't understand why. 
Please note that using a "standard" Kafka Consumer, everything works fine.
What am i doing wrong? 

Thanks in advance!

Mauro

**Comment by astubbs** [comment]
Can you include the logs or a complete example? Looks fine.

**Comment by mroiter-larus** [comment]
@astubbs, Thanks for your answer! In attachment you will find both the complete example and the log file.
Enabling the log i found the following exception coming from the library:

```
[control] ERROR io.confluent.parallelconsumer.ParallelEoSStreamProcessor  - Error from poll control thread, will attempt controlled shutdown, then rethrow. Error: Error in BrokerPollSystem system.
io.confluent.parallelconsumer.InternalRuntimeError: Error in BrokerPollSystem system.
	at io.confluent.parallelconsumer.BrokerPollSystem.supervise(BrokerPollSystem.java:87)
	at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.controlLoop(ParallelEoSStreamProcessor.java:676)
	at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.lambda$supervisorLoop$10(ParallelEoSStreamProcessor.java:607)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.Consumer.committed(Ljava/util/Set;)Ljava/util/Map;
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at io.confluent.parallelconsumer.BrokerPollSystem.supervise(BrokerPollSystem.java:85)
	... 6 more
Caused by: java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.Consumer.committed(Ljava/util/Set;)Ljava/util/Map;
	at io.confluent.parallelconsumer.OffsetMapCodecManager.loadOffsetMapForPartition(OffsetMapCodecManager.java:105)
	at io.confluent.parallelconsumer.WorkManager.onPartitionsAssigned(WorkManager.java:181)
	at io.confluent.parallelconsumer.ParallelEoSStreamProcessor.onPartitionsAssigned(ParallelEoSStreamProcessor.java:291)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:283)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:422)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:352)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:337)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:333)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1218)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1175)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154)
	at io.confluent.parallelconsumer.ConsumerManager.poll(ConsumerManager.java:41)
	at io.confluent.parallelconsumer.BrokerPollSystem.pollBrokerForRecords(BrokerPollSystem.java:185)
	at io.confluent.parallelconsumer.BrokerPollSystem.controlLoop(BrokerPollSystem.java:105)
	... 4 more
```

[kafka-parallel-consumer-test.zip](https://github.com/confluentinc/parallel-consumer/files/6196859/kafka-parallel-consumer-test.zip)
[kafka-parallel-consumer-test.log](https://github.com/confluentinc/parallel-consumer/files/6196860/kafka-parallel-consumer-test.log)

**Comment by mroiter-larus** [comment]
@astubbs I found the reason of the exception. It was raised because i was using an old version of the `kafka-clients` library. Upgrading to the latest, 2.7.0, the exception is not raised anymore.
However, it seems that the parallel consumer is still not finding any message to consume.

In attachment you will find the updated version of the example source code (with the upgraded `kafka-clients`)

[kafka-parallel-consumer-test.zip](https://github.com/confluentinc/parallel-consumer/files/6197636/kafka-parallel-consumer-test.zip)

**Comment by astubbs** [comment]
> i was using an old version of the Kafka-clients
What version were you using?

Thanks for the code, but can you add a test to it which reproduces the problem? If you a unit test doesn't do it, try an integration test with test containers. Happy to help where I can, but I don't have much time :) I'm curious to see what the issues is though..

**Comment by mroiter-larus** [comment]
I solved the problem! Obviously it wasn't an issue with the parallel consumer library. Since i used 2 consumers, the standard and the parallel, i forgot to assign different `group.id` to them. My bad!

Thanks anyway for your availability!
